# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 500))
        MainWindow.setMaximumSize(QtCore.QSize(1400, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.stackedWidget.setMinimumSize(QtCore.QSize(120, 100))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.pushButton = QtWidgets.QPushButton(self.home)
        self.pushButton.setGeometry(QtCore.QRect(70, 150, 200, 180))
        self.pushButton.setMinimumSize(QtCore.QSize(200, 180))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.home)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 150, 200, 180))
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 180))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.home)
        self.pushButton_3.setGeometry(QtCore.QRect(540, 150, 200, 180))
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 180))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.home)
        self.user_profile = QtWidgets.QWidget()
        self.user_profile.setObjectName("user_profile")
        self.label = QtWidgets.QLabel(self.user_profile)
        self.label.setGeometry(QtCore.QRect(270, 240, 55, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.user_profile)
        self.lineEdit.setGeometry(QtCore.QRect(390, 240, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.user_profile)
        self.label_4.setGeometry(QtCore.QRect(340, 70, 55, 16))
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.user_profile)
        self.user_posts = QtWidgets.QWidget()
        self.user_posts.setObjectName("user_posts")
        self.label_2 = QtWidgets.QLabel(self.user_posts)
        self.label_2.setGeometry(QtCore.QRect(300, 210, 55, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.user_posts)
        self.lineEdit_2.setGeometry(QtCore.QRect(420, 210, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.user_posts)
        self.label_3.setGeometry(QtCore.QRect(360, 30, 55, 16))
        self.label_3.setObjectName("label_3")
        self.stackedWidget.addWidget(self.user_posts)
        self.random_tweets = QtWidgets.QWidget()
        self.random_tweets.setObjectName("random_tweets")
        self.stackedWidget.addWidget(self.random_tweets)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "User \n"
" Profile Data"))
        self.pushButton_2.setText(_translate("MainWindow", "All User \n"
" Posts"))
        self.pushButton_3.setText(_translate("MainWindow", "Random \n"
" Tweets"))
        self.label.setText(_translate("MainWindow", "Profile url"))
        self.label_4.setText(_translate("MainWindow", "Profile Data"))
        self.label_2.setText(_translate("MainWindow", "Profile url"))
        self.label_3.setText(_translate("MainWindow", "User Posts"))
